### ISSUE TITLE
Function CleanData is not working properly

### ISSUE THREAD

**Issue by JuliaPetranova** [nandakallugjeri/bmarketing#4]
Error message attached:

> bmarketing:::cleanData(bmarketing2, bmarketing2$CAMPAIGN)
Error in bmarketing:::cleanData(bmarketing2, bmarketing2$CAMPAIGN) : TRUE
In addition: Warning message:
In if (targetVar %in% colnames(ds) == FALSE) stop(targetVar || "variable not part of the dataframe passed") :
  the condition has length > 1 and only the first element will be used
> bmarketing:::cleanData(bmarketing2, bmarketing2$AGE)
Error in bmarketing:::cleanData(bmarketing2, bmarketing2$AGE) : TRUE
In addition: Warning message:
In if (targetVar %in% colnames(ds) == FALSE) stop(targetVar || "variable not part of the dataframe passed") :
  the condition has length > 1 and only the first element will be used

**Comment by nandakallugjeri** [comment]
Fixed. thanks
